# This overlay builds the visibility component to be used in combination
# with other overlays.

namespace: kueue-system
namePrefix: kueue-
resources:
- ../components/visibility

transformers:
# Sets the namespace for the role binding as kube-system instead of default kueue-system
- role_binding_visibility_transformer.yaml